[run]
build = "npm run build"
test = "npm run test"
lint = "npm run lint"

[paths]
dist = "./dist"  # base directory to sd in (for monorepos)
src = "./src" 


[gptengineer-app]
project_id = "74439ff3-8fd7-49a1-ac97-bc4505ab2bab"
